In [3]:
import numpy as np

In [3]:
array = np.array((1, 2.5, 4))
array

array([1. , 2.5, 4. ])

In [4]:
print(array)

[1.  2.5 4. ]


In [5]:
print(type(array))

<class 'numpy.ndarray'>


#### Dimension in Arrays

##### 0, 1, 2, 3-D arrays

In [6]:
array = np.array(42)
print(array)
print(type(array))

42
<class 'numpy.ndarray'>


In [7]:
array.ndim

0

In [8]:
array1 = np.array([[[42, 21], [14, 7]], [[3.5, 1.75], [0, 1]]]) #3-D array
print(array1)
print(type(array1))
print(array1.ndim)

[[[42.   21.  ]
  [14.    7.  ]]

 [[ 3.5   1.75]
  [ 0.    1.  ]]]
<class 'numpy.ndarray'>
3


In [9]:
array = np.array([1,2,3], ndmin = 3)
print(array)

[[[1 2 3]]]


### Array Indexing

In [10]:
array1[0]

array([[42., 21.],
       [14.,  7.]])

In [11]:
array1[0][0]

array([42., 21.])

In [12]:
array1[0][0][0]

42.0

In [13]:
print(f"Second element in Array 1 is {array1[0,0,1]}")

Second element in Array 1 is 21.0


In [14]:
print(f"Second element in Array 1 is {array1[0,0,-1]}")
print(f"first element in Array 1 is {array1[0,0,-2]}") #Negative Indexing

Second element in Array 1 is 21.0
first element in Array 1 is 42.0


#### NumPy Array Slicing


In [21]:
a2 = np.array([1,2,3,4.5,6,7,8,9,11,12])
print(a2.ndim)
print(a2[::2])

1
[ 1.  3.  6.  8. 11.]


In [27]:
print(a2[-6:-1])

[ 6.  7.  8.  9. 11.]


In [68]:
print(array1[0][0][0])
print(array1[0][1][0])

42.0
14.0


### Data Types in Numpy

In [77]:
Arr2 = np.array([1,2,3,4], dtype = 'S')
print(Arr2)

[b'1' b'2' b'3' b'4']


In [78]:
Arr2 = np.array([1,2,3,4], dtype = 'f')
print(Arr2)

[1. 2. 3. 4.]


In [79]:
Arr3 = np.array([1.2, 3.4, 5., 6.5], dtype = 'f')
Arr3

array([1.2, 3.4, 5. , 6.5], dtype=float32)

In [81]:
arraynew = Arr3.astype(bool)
arraynew

array([ True,  True,  True,  True])

### Array (Re)Shapes

In [84]:
Arr3.shape

(4,)

In [85]:
Arr3.reshape(2,2)

array([[1.2, 3.4],
       [5. , 6.5]], dtype=float32)

In [86]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


### Iterating

In [4]:
arr = np.array([[1,2,3],[4,5,6]])

In [5]:
for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [6]:
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


In [9]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6


In [15]:
for i in np.nditer(arr, flags = ['buffered'], op_dtypes = 'S'):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


In [16]:
for idx, x in np.ndenumerate(arr):
     print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [17]:
arr[0][1]

2

In [25]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
arR = np.hstack((arr1,arr2))
print(arr == arR)

[ True  True  True  True  True  True]


In [28]:
print(np.vstack((arr1,arr2)))
print("\n")
print(np.dstack((arr1,arr2)))

[[1 2 3]
 [4 5 6]]


[[[1 4]
  [2 5]
  [3 6]]]
