In [1]:
import numpy as np

In [2]:
array = np.array((1, 2.5, 4))
array

array([1. , 2.5, 4. ])

In [3]:
print(array)

[1.  2.5 4. ]


In [4]:
print(type(array))

<class 'numpy.ndarray'>


#### Dimension in Arrays

##### 0, 1, 2, 3-D arrays

In [6]:
array = np.array(42)
print(array)
print(type(array))

42
<class 'numpy.ndarray'>


In [7]:
array.ndim

0

In [24]:
array1 = np.array([[[42, 21], [14, 7]], [[3.5, 1.75], [0, 1]]]) #3-D array
print(array1)
print(type(array1))
print(array1.ndim)

[[[42.   21.  ]
  [14.    7.  ]]

 [[ 3.5   1.75]
  [ 0.    1.  ]]]
<class 'numpy.ndarray'>
3


In [21]:
array = np.array([1,2,3], ndmin = 3)
print(array)

[[[1 2 3]]]


### Array Indexing

In [27]:
array1[0]

array([[42., 21.],
       [14.,  7.]])

In [28]:
array1[0][0]

array([42., 21.])

In [29]:
array1[0][0][0]

42.0

In [30]:
print(f"Second element in Array 1 is {array1[0,0,1]}")

Second element in Array 1 is 21.0


In [33]:
print(f"Second element in Array 1 is {array1[0,0,-1]}")
print(f"first element in Array 1 is {array1[0,0,-2]}") #Negative Indexing

Second element in Array 1 is 21.0
first element in Array 1 is 42.0
