In [1]:
import numpy as np

In [2]:
array = np.array((1, 2.5, 4))
array

array([1. , 2.5, 4. ])

In [3]:
print(array)

[1.  2.5 4. ]


In [4]:
print(type(array))

<class 'numpy.ndarray'>


#### Dimension in Arrays

##### 0, 1, 2, 3-D arrays

In [6]:
array = np.array(42)
print(array)
print(type(array))

42
<class 'numpy.ndarray'>


In [7]:
array.ndim

0

In [20]:
array = np.array([[[42, 21], [14, 7]], [[3.5, 1.75], [0, 1]]]) #3-D array
print(array)
print(type(array))
print(array.ndim)

[[[42.   21.  ]
  [14.    7.  ]]

 [[ 3.5   1.75]
  [ 0.    1.  ]]]
<class 'numpy.ndarray'>
3


In [21]:
array = np.array([1,2,3], ndmin = 3)
print(array)

[[[1 2 3]]]
